version: "3.1"

services:
  onebyone-postgres:
    container_name: "onebyone-postgres"
    image: postgres
    restart: unless-stopped
    env_file:
      - ./application.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data


