apiVersion : apps/v1
kind: Deployment
metadata:
  name: "onebyone-api"
  labels:
    aadpodidbinding: azure-pod-identity-binding-selector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "onebyone-api"
  template:
    metadata:
      labels:
        app: "onebyone-api"
    spec:
      containers:
        - name: "onebyone-api"
          image: "onebyonedr.azurecr.io/onebyoneaks"
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://onebyone-db.postgres.database.azure.com:5432/onebyone
            - name: SPRING_DATASOURCE_USERNAME
              value: sbailleul@onebyone-db
            - name: SPRING_DATASOURCE_PASSWORD
              value: votu5632?,
