apiVersion : apps/v1
kind: Deployment
metadata:
  name: "onebyoneaks-cc2d"
  labels:
    aadpodidbinding: azure-pod-identity-binding-selector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "onebyoneaks-cc2d"
  template:
    metadata:
      labels:
        app: "onebyoneaks-cc2d"
    spec:
      containers:
        - name: "onebyoneaks-cc2d"
          image: "onebyonedr.azurecr.io/onebyoneaks"
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://onebyone-db.postgres.database.azure.com:5432/onebyone
            - name: SPRING_DATASOURCE_USERNAME
              value: sbailleul@onebyone-db
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onebyone-db-pwd-secret
                  key: key
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: spc-onebyone-kv
