apiVersion : apps/v1
kind: Deployment
metadata:
  name: "onebyoneaks-cc2d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "onebyoneaks-cc2d"
  template:
    metadata:
      labels:
        app: "onebyoneaks-cc2d"
    spec:
      containers:
        - name: "onebyoneaks-cc2d"
          image: "onebyonedr.azurecr.io/onebyoneaks"
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://onebyone-db.postgres.database.azure.com:5432/onebyone
            - name: SPRING_DATASOURCE_USERNAME
              value: sbailleul@onebyone
            - name: SPRING_DATASOURCE_PASSWORD
              value: votu5632?,


