version: "3.1"

services:
  onebyone-api:
    container_name: onebyone-api
    restart: unless-stopped
    image: onebyone/api
    working_dir: /app
    build:
      dockerfile: Dockerfile
      context: ../api
    env_file:
      - ./application.env
    ports:
      - 8082:8080
  onebyone-api-cloud-test:
    container_name: onebyone-api-cloud-test
    restart: unless-stopped
    image: onebyone/api
    working_dir: /app
    build:
      dockerfile: Dockerfile
      context: ../api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://onebyone-db.postgres.database.azure.com:5432/onebyone"
      SPRING_DATASOURCE_USERNAME: "sbailleul@onebyone-db"
      SPRING_DATASOURCE_PASSWORD: "votu5632?,"
    ports:
      - 8083:8080

  onebyone-postgres:
    container_name: onebyone-postgres
    image: postgres
    restart: unless-stopped
    env_file:
      - ./application.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data


