on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n onebyone -g onebyone9e6a-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n onebyone --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n onebyone --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n onebyone --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: onebyone.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/api" -f  "api/Dockerfile" -t onebyone.azurecr.io/onebyone-api:${{ github.sha }} --label dockerfile-path=api/Dockerfile
        docker push onebyone.azurecr.io/onebyone-api:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_onebyoneaks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: onebyone.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: onebyoneaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          onebyone.azurecr.io/onebyone-api:${{ github.sha }}
        imagepullsecrets: |
          onebyoneaksdockerauth   
